// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internalcom.proto

#ifndef PROTOBUF_internalcom_2eproto__INCLUDED
#define PROTOBUF_internalcom_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_internalcom_2eproto();
void protobuf_AssignDesc_internalcom_2eproto();
void protobuf_ShutdownFile_internalcom_2eproto();

class Order;
class OrderReply;

// ===================================================================

class Order : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Order) */ {
 public:
  Order();
  virtual ~Order();

  Order(const Order& from);

  inline Order& operator=(const Order& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Order& default_instance();

  void Swap(Order* other);

  // implements Message ----------------------------------------------

  inline Order* New() const { return New(NULL); }

  Order* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Order& from);
  void MergeFrom(const Order& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Order* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 shipid = 1;
  bool has_shipid() const;
  void clear_shipid();
  static const int kShipidFieldNumber = 1;
  ::google::protobuf::int64 shipid() const;
  void set_shipid(::google::protobuf::int64 value);

  // required int32 whid = 2;
  bool has_whid() const;
  void clear_whid();
  static const int kWhidFieldNumber = 2;
  ::google::protobuf::int32 whid() const;
  void set_whid(::google::protobuf::int32 value);

  // required int32 delX = 3;
  bool has_delx() const;
  void clear_delx();
  static const int kDelXFieldNumber = 3;
  ::google::protobuf::int32 delx() const;
  void set_delx(::google::protobuf::int32 value);

  // required int32 delY = 4;
  bool has_dely() const;
  void clear_dely();
  static const int kDelYFieldNumber = 4;
  ::google::protobuf::int32 dely() const;
  void set_dely(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Order)
 private:
  inline void set_has_shipid();
  inline void clear_has_shipid();
  inline void set_has_whid();
  inline void clear_has_whid();
  inline void set_has_delx();
  inline void clear_has_delx();
  inline void set_has_dely();
  inline void clear_has_dely();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 shipid_;
  ::google::protobuf::int32 whid_;
  ::google::protobuf::int32 delx_;
  ::google::protobuf::int32 dely_;
  friend void  protobuf_AddDesc_internalcom_2eproto();
  friend void protobuf_AssignDesc_internalcom_2eproto();
  friend void protobuf_ShutdownFile_internalcom_2eproto();

  void InitAsDefaultInstance();
  static Order* default_instance_;
};
// -------------------------------------------------------------------

class OrderReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OrderReply) */ {
 public:
  OrderReply();
  virtual ~OrderReply();

  OrderReply(const OrderReply& from);

  inline OrderReply& operator=(const OrderReply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OrderReply& default_instance();

  void Swap(OrderReply* other);

  // implements Message ----------------------------------------------

  inline OrderReply* New() const { return New(NULL); }

  OrderReply* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const OrderReply& from);
  void MergeFrom(const OrderReply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(OrderReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 shipid = 1;
  bool has_shipid() const;
  void clear_shipid();
  static const int kShipidFieldNumber = 1;
  ::google::protobuf::int64 shipid() const;
  void set_shipid(::google::protobuf::int64 value);

  // optional string error = 2;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // @@protoc_insertion_point(class_scope:OrderReply)
 private:
  inline void set_has_shipid();
  inline void clear_has_shipid();
  inline void set_has_error();
  inline void clear_has_error();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 shipid_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  friend void  protobuf_AddDesc_internalcom_2eproto();
  friend void protobuf_AssignDesc_internalcom_2eproto();
  friend void protobuf_ShutdownFile_internalcom_2eproto();

  void InitAsDefaultInstance();
  static OrderReply* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Order

// required int64 shipid = 1;
inline bool Order::has_shipid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Order::set_has_shipid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Order::clear_has_shipid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Order::clear_shipid() {
  shipid_ = GOOGLE_LONGLONG(0);
  clear_has_shipid();
}
inline ::google::protobuf::int64 Order::shipid() const {
  // @@protoc_insertion_point(field_get:Order.shipid)
  return shipid_;
}
inline void Order::set_shipid(::google::protobuf::int64 value) {
  set_has_shipid();
  shipid_ = value;
  // @@protoc_insertion_point(field_set:Order.shipid)
}

// required int32 whid = 2;
inline bool Order::has_whid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Order::set_has_whid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Order::clear_has_whid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Order::clear_whid() {
  whid_ = 0;
  clear_has_whid();
}
inline ::google::protobuf::int32 Order::whid() const {
  // @@protoc_insertion_point(field_get:Order.whid)
  return whid_;
}
inline void Order::set_whid(::google::protobuf::int32 value) {
  set_has_whid();
  whid_ = value;
  // @@protoc_insertion_point(field_set:Order.whid)
}

// required int32 delX = 3;
inline bool Order::has_delx() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Order::set_has_delx() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Order::clear_has_delx() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Order::clear_delx() {
  delx_ = 0;
  clear_has_delx();
}
inline ::google::protobuf::int32 Order::delx() const {
  // @@protoc_insertion_point(field_get:Order.delX)
  return delx_;
}
inline void Order::set_delx(::google::protobuf::int32 value) {
  set_has_delx();
  delx_ = value;
  // @@protoc_insertion_point(field_set:Order.delX)
}

// required int32 delY = 4;
inline bool Order::has_dely() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Order::set_has_dely() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Order::clear_has_dely() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Order::clear_dely() {
  dely_ = 0;
  clear_has_dely();
}
inline ::google::protobuf::int32 Order::dely() const {
  // @@protoc_insertion_point(field_get:Order.delY)
  return dely_;
}
inline void Order::set_dely(::google::protobuf::int32 value) {
  set_has_dely();
  dely_ = value;
  // @@protoc_insertion_point(field_set:Order.delY)
}

// -------------------------------------------------------------------

// OrderReply

// required int64 shipid = 1;
inline bool OrderReply::has_shipid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OrderReply::set_has_shipid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OrderReply::clear_has_shipid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OrderReply::clear_shipid() {
  shipid_ = GOOGLE_LONGLONG(0);
  clear_has_shipid();
}
inline ::google::protobuf::int64 OrderReply::shipid() const {
  // @@protoc_insertion_point(field_get:OrderReply.shipid)
  return shipid_;
}
inline void OrderReply::set_shipid(::google::protobuf::int64 value) {
  set_has_shipid();
  shipid_ = value;
  // @@protoc_insertion_point(field_set:OrderReply.shipid)
}

// optional string error = 2;
inline bool OrderReply::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OrderReply::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OrderReply::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OrderReply::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_error();
}
inline const ::std::string& OrderReply::error() const {
  // @@protoc_insertion_point(field_get:OrderReply.error)
  return error_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OrderReply::set_error(const ::std::string& value) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OrderReply.error)
}
inline void OrderReply::set_error(const char* value) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OrderReply.error)
}
inline void OrderReply::set_error(const char* value, size_t size) {
  set_has_error();
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OrderReply.error)
}
inline ::std::string* OrderReply::mutable_error() {
  set_has_error();
  // @@protoc_insertion_point(field_mutable:OrderReply.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OrderReply::release_error() {
  // @@protoc_insertion_point(field_release:OrderReply.error)
  clear_has_error();
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OrderReply::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    set_has_error();
  } else {
    clear_has_error();
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:OrderReply.error)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_internalcom_2eproto__INCLUDED
