# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170420_0211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipmentTracker',
            new_name='ShipmentItem',
        ),
    ]
