# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_trackingnumber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingnumber',
            name='truck_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingnumber',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingnumber',
            name='x_address',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingnumber',
            name='y_address',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='truck_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
