# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20170429_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingnumber',
            name='ups_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
