# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_trackingnumber_ups_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
