# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_inventory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingnumber',
            name='ups_num',
            field=models.IntegerField(null=True),
        ),
    ]
