# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20170429_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_ratings',
            field=models.FloatField(),
        ),
    ]
