# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20170501_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
