# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_shipmentitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingnumber',
            name='ups_num',
            field=models.BigIntegerField(null=True),
        ),
    ]
